name: Welcome First Time Contributors

on: 
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Welcome to the repository! Feel free to open an issue if you face any problem.'
          pr-message: '🎉 Thanks for opening your first pull request! We appreciate your contribution.'
